#!/usr/bin/tclsh

if {[info exists env(ERRTAGS_CACHE_FILE)]} {
    set outputFilename $env(ERRTAGS_CACHE_FILE)
} elseif {[info exists env(XDG_CACHE_HOME)]} {
    set outputFilename "$env(XDG_CACHE_HOME)/errtags.tags"
} else {
    puts stderr [string cat \
        "errtags: Could not find your cache folder. " \
        "Set \$ERRTAGS_CACHE_FILE in the environment!"
    ]
    exit 1
}

if {[info exists env(ERRTAGS_SESSION)]} {
    set ERRTAGS_SESSION $env(ERRTAGS_SESSION)
} else {
    set ERRTAGS_SESSION ""
}

if {$ERRTAGS_SESSION eq ""} {
    set ERRTAGS_SESSION [expr {int(rand() * 1000) + 1}]
}

# --- Setup output
proc getMode {fileName errtagsSession} {
    if {[catch {set fileId [open $fileName r]}]} { return "w" }
    
    set firstLine [gets $fileId]
    close $fileId

    return [expr {[string match "#$errtagsSession" $firstLine] ? "a" : "w"}]
}

set mode [getMode $outputFilename $ERRTAGS_SESSION]

set output [open $outputFilename $mode]

# --- Header rewrite
if {$mode == "w"} {
    puts $output "#$ERRTAGS_SESSION"
}

# --- Error translation
set errex {(.+):(\d+):(\d+): error: (.*)}
while {[gets stdin line] >= 0} {
    if {[regexp $errex $line ignore sfile sline scol msg]} {
        puts $output "$sfile:$sline:$scol:$msg"
    }
}
close $output
