#!/bin/bash
self=$(readlink -f "$0")
next_cc=$(
    which -a cc |
    while IFS= read -r p; do
        [ "$(readlink -f "$p")" != "$self" ] && { echo "$p"; break; }
    done
)

$next_cc -fdiagnostics-color=always "$@" 2>&1 \
| tee >(\
        sed -e 's/\x1b\[[0-9;]*m//g' -e 's/\x1b\[K//g' \
        | errtags
)

exit ${PIPESTATUS[0]}
